services:
  app:
    build: .
    container_name: CrazyWalk-Frontend
    restart: always
    ports:
      - "80:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6500
      - PYTHONDONTWRITEBYTECODE=1
    networks:
      - pc2-net

  webhook:
    build:
      context: ./CORE/TOOLS/AUTOUPDATE_WEBHOOK_FROM_GITHUB
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    env_file:
      - .env
    environment:
      - AUTOUPDATE_WEBHOOK_FROM_GITHUB=${AUTOUPDATE_WEBHOOK_FROM_GITHUB}
      - FRONTEND_INDEX_PAGE=CORE/FRONTEND
    networks:
      - pc2-net

  redis:
    image: redis:alpine
    container_name: CrazyWalk-Redis
    restart: always
    command: redis-server --port 6500
    ports:
      - "6500:6500"
    networks:
      - pc2-net

networks:
  pc2-net:
    external: true
    name: pc2-net
